<a href="https://colab.research.google.com/github/Priyadharshini394/CODSOFT/blob/main/BookRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow.keras as tf

In [ ]:
ratings = pd.read_csv("/ratings.csv.zip")
books = pd.read_csv("/books.csv.zip")


In [ ]:
ratings.head()

book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [ ]:
books.head()

id  book_id  best_book_id  work_id  books_count       isbn        isbn13  \
0   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
1   2        3             3  4640799          491  439554934  9.780440e+12   
2   3    41865         41865  3212258          226  316015849  9.780316e+12   
3   4     2657          2657  3275794          487   61120081  9.780061e+12   
4   5     4671          4671   245494         1356  743273567  9.780743e+12   

                       authors  original_publication_year  \
0              Suzanne Collins                     2008.0   
1  J.K. Rowling, Mary GrandPré                     1997.0   
2              Stephenie Meyer                     2005.0   
3                   Harper Lee                     1960.0   
4          F. Scott Fitzgerald                     1925.0   

                             original_title  ... ratings_count  \
0                          The Hunger Games  ...       4780653   
1  Harry Potter and the Philosopher's Stone  ...       4602479   
2                                  Twilight  ...       3866839   
3                     To Kill a Mockingbird  ...       3198671   
4                          The Great Gatsby  ...       2683664   

  work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
0            4942365                   155254      66715     127936   
1            4800065                    75867      75504     101676   
2            3916824                    95009     456191     436802   
3            3340896                    72586      60427     117415   
4            2773745                    51992      86236     197621   

   ratings_3  ratings_4  ratings_5  \
0     560092    1481305    2706317   
1     455024    1156318    3011543   
2     793319     875073    1355439   
3     446835    1001952    1714267   
4     606158     936012     947718   

                                           image_url  \
0  https://images.gr-assets.com/books/1447303603m...   
1  https://images.gr-assets.com/books/1474154022m...   
2  https://images.gr-assets.com/books/1361039443m...   
3  https://images.gr-assets.com/books/1361975680m...   
4  https://images.gr-assets.com/books/1490528560m...   

                                     small_image_url  
0  https://images.gr-assets.com/books/1447303603s...  
1  https://images.gr-assets.com/books/1474154022s...  
2  https://images.gr-assets.com/books/1361039443s...  
3  https://images.gr-assets.com/books/1361975680s...  
4  https://images.gr-assets.com/books/1490528560s...  

[5 rows x 23 columns]

In [ ]:
nbooks = ratings.book_id.nunique()
nusers = ratings.user_id.nunique()

In [ ]:
print(nbooks)
print(nusers)

10000
53424


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test = train_test_split(ratings,test_size=0.2,random_state=10)

In [ ]:
book_input = tf.Input(shape=[1])# [None,1] [64,1]
book_embedding = tf.layers.Embedding(nbooks+1,15)(book_input)
book_out = tf.layers.Flatten()(book_embedding)

user_input = tf.Input(shape=[1])# [None,1] [64,1]
user_embedding = tf.layers.Embedding(nusers+1,15)(user_input)
user_out = tf.layers.Flatten()(user_embedding)

concadinate = tf.layers.Concatenate()([book_out,user_out])
dense_1 = tf.layers.Dense(128,activation='relu')(concadinate)
out = tf.layers.Dense(1,activation="relu")(dense_1)

model = tf.Model([book_input,user_input],out)



In [ ]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_11 (InputLayer)       [(None, 1)]                  0         []                            
                                                                                                  
 input_12 (InputLayer)       [(None, 1)]                  0         []                            
                                                                                                  
 embedding_8 (Embedding)     (None, 1, 15)                150015    ['input_11[0][0]']            
                                                                                                  
 embedding_9 (Embedding)     (None, 1, 15)                801375    ['input_12[0][0]']            
                                                                                            

In [ ]:
model.compile(optimizer='adam',loss="mean_squared_error")


In [ ]:
model.fit([x_train.book_id,x_train.user_id],x_train.rating,validation_data=([x_test.book_id,x_test.user_id],x_test.rating),epochs=5,batch_size=64)


Epoch 1/5
12272/12272 [==============================] - 218s 18ms/step - loss: 0.7468 - val_loss: 0.7148
Epoch 2/5
12272/12272 [==============================] - 215s 18ms/step - loss: 0.6807 - val_loss: 0.6967
Epoch 3/5
12272/12272 [==============================] - 224s 18ms/step - loss: 0.6461 - val_loss: 0.6955
Epoch 4/5
12272/12272 [==============================] - 221s 18ms/step - loss: 0.6167 - val_loss: 0.6973
Epoch 5/5
12272/12272 [==============================] - 214s 17ms/step - loss: 0.5878 - val_loss: 0.7044


In [ ]:
model.save("recommander")

In [ ]:
b_id=list(ratings.book_id.unique())

In [ ]:
b_id

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [ ]:
book_arr=np.array(b_id) #get all book 10s
user=np.array([80 for i in range(len(b_id))])

In [ ]:
pred=model.predict([book_arr,user])
pred

313/313 [==============================] - 1s 2ms/step


array([[3.8006551],
       [3.9482439],
       [2.2798622],
       ...,
       [3.9031923],
       [3.4308245],
       [3.518792 ]], dtype=float32)

In [ ]:
pred=pred.reshape(-1)
pred

array([3.8006551, 3.9482439, 2.2798622, ..., 3.9031923, 3.4308245,
       3.518792 ], dtype=float32)

In [ ]:
pred_ids=(-pred).argsort()[0:5]
pred_ids

array([8108, 9565, 7946, 3627, 6589])

In [ ]:
books.iloc[pred_ids]

id  book_id  best_book_id   work_id  books_count        isbn  \
8108  8109    23753         23753   1789924            5  1401210821   
9565  9566    70487         70487   2244439           24  1417642165   
7946  7947  5031805       5031805  40769318           96  1433502410   
3627  3628    24812         24812     25599           14   740748475   
6589  6590    59715         59715   1010526           21   751507954   

            isbn13                                            authors  \
8108  9.781401e+12  Neil Gaiman, Mike Dringenberg, Chris Bachalo, ...   
9565  9.781418e+12                                     Bill Watterson   
7946  9.781434e+12         Anonymous, Lane T. Dennis, Wayne A. Grudem   
3627  9.780741e+12                                     Bill Watterson   
6589  9.780752e+12                                     Bill Watterson   

      original_publication_year  \
8108                     2006.0   
9565                     1992.0   
7946                     2002.0   
3627                     2005.0   
6589                     1990.0   

                                         original_title  ... ratings_count  \
8108                   The Absolute Sandman, Volume One  ...         13401   
9565  Attack of the Deranged Mutant Killer Monster S...  ...          9713   
7946                                                NaN  ...          8953   
3627                     The Complete Calvin and Hobbes  ...         28900   
6589                The Authoritative Calvin and Hobbes  ...         16087   

     work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
8108              13726                      476         72        128   
9565              12197                      233         15         30   
7946              10784                      262         98         90   
3627              29968                      861        120        154   
6589              18198                      425         20         61   

      ratings_3  ratings_4  ratings_5  \
8108        684       2744      10098   
9565        514       2292       9346   
7946        367       1152       9077   
3627        693       3117      25884   
6589        701       3295      14121   

                                              image_url  \
8108  https://images.gr-assets.com/books/1312226853m...   
9565  https://images.gr-assets.com/books/1384735429m...   
7946  https://images.gr-assets.com/books/1410151002m...   
3627  https://images.gr-assets.com/books/1473064526m...   
6589  https://images.gr-assets.com/books/1391114055m...   

                                        small_image_url  
8108  https://images.gr-assets.com/books/1312226853s...  
9565  https://images.gr-assets.com/books/1384735429s...  
7946  https://images.gr-assets.com/books/1410151002s...  
3627  https://images.gr-assets.com/books/1473064526s...  
6589  https://images.gr-assets.com/books/1391114055s...  

[5 rows x 23 columns]